from fpdf import FPDF
from datetime import datetime

class ForensicReport(FPDF):
    def header(self):
        self.set_font('Courier', 'B', 16)
        self.set_text_color(139, 0, 0) # Dark Red
        self.cell(0, 10, 'CLASSIFIED: FORENSIC INVESTIGATION DOSSIER', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Courier', 'I', 8)
        self.cell(0, 10, f'Generated by ForensiX Suite // Investigator: Sanskar Dhore // Page {self.page_no()}', 0, 0, 'C')

def clean_text(text):
    """Removes non-latin characters to prevent UnicodeEncodeError"""
    return str(text).encode('latin-1', 'ignore').decode('latin-1')

def create_pdf_report(results_list, case_notes="No manual notes provided."):
    pdf = ForensicReport()
    pdf.add_page()
    pdf.set_font("Courier", size=12)

    # Global Case Details
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, txt=f"REPORT GENERATED: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 10, txt=f"TOTAL EXHIBITS ANALYZED: {len(results_list)}", ln=True)
    pdf.ln(5)

    # Investigator's Conclusion Section
    pdf.set_font("Courier", 'B', 14)
    pdf.set_text_color(139, 0, 0)
    pdf.cell(0, 10, txt="INVESTIGATOR'S FINAL CONCLUSION:", ln=True)
    pdf.set_font("Courier", size=11)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 7, txt=clean_text(case_notes))
    pdf.ln(10)
    pdf.cell(0, 0, '', 'T') # Horizontal Line
    pdf.ln(10)

    # Results Loop
    for res in results_list:
        pdf.set_font("Courier", 'B', 13)
        pdf.set_text_color(139, 0, 0)
        pdf.cell(0, 10, txt=f"EXHIBIT: {clean_text(res['FILENAME'])}", ln=True)
        
        pdf.set_font("Courier", size=11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 8, txt=f"VERDICT: {clean_text(res['VERDICT'])}", ln=True)
        pdf.cell(0, 8, txt=f"AI CONFIDENCE: {res['PROBABILITY']}", ln=True)
        
        pdf.set_font("Courier", 'B', 11)
        pdf.cell(0, 8, txt="METADATA AUDIT:", ln=True)
        pdf.set_font("Courier", size=10)
        pdf.multi_cell(0, 6, txt=clean_text(res['METADATA_TRACE']))
        
        pdf.ln(5)
        pdf.cell(0, 0, '', 'T')
        pdf.ln(10)

    return pdf.output(dest='S').encode('latin-1')